theme: minima
author: NateDhaliwal
title: NateDhaliwal's Blog
description: This is NateDhaliwal's Blog, where he is doing this using Jekyll and Github Pages. He's pretty new to this, and he tries to write blog posts frequently.
permalink: /post/:categories/:year/:month/:day/:title:output_ext
# excerpt_separator: <!--excerptend-->
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/natedhaliwal/natedhaliwal" }

show_excerpts: true
JEKYLL_ENV: production
