theme: minima
author: NateDhaliwal
title: NateDhaliwal's Blog
description: This is NateDhaliwal's Blog, where he is doing this using Jekyll and Github Pages. He's pretty new to this, and he tries to write blog posts frequently.
